CREATE TABLE IF NOT EXISTS PasswordResetToken (
  TokenID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TokenHash VARCHAR(128) NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  UsedAt DATETIME NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  INDEX idx_token_hash (TokenHash)
);